apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure repository
  title: Azure Repository
  description: Create a new azure repository
  tags:
    - recommended
    - cloud-azure
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
        - service
      properties:
        name:
          title: Repository Name
          type: string
          description: The name of the repository
          ui:autofocus: true
          ui:options:
            rows: 5
        service:
          title: Service Name
          type: string
          description: The name of the service
          ui:autofocus: true
          ui:options:
            rows: 5
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: https://github.com/luis-henrique-carvalho/azure_api_template
        values:
          name: ${{ parameters.name }}
          service: ${{ parameters.service }}

    - id: publish-azure
      name: Publish to Azure DevOps
      action: publish:azure
      input:
        allowedHosts: ["dev.azure.com"]
        description: This is ${{ parameters.projectName }}
        repoUrl: ${{ env.REPO_URL }}
        project: ${{ env.PROJECT }}
        organization: ${{ env.ORGANIZATION }}

    - id: register-azure
      name: Register in Azure DevOps
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-azure'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - id: create-branch
      name: Create Branch
      action: azure:create-branch
      input:
        repository: ${{ parameters.name }}
        organization: ${{ env.ORGANIZATION }}
        project: ${{ env.PROJECT }}
        branchNames: ["develop", "qa", "uat"]

  output:
    links:
      - title: Repository
        url: ${{ steps['publish-azure'].output.remoteUrl }}?path=%2F
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register-azure'].output.entityRef }}
