apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-repository
  title: Azure Repository
  description: Create a new azure repository
  tags:
    - recommended
    - cloud-azure
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
        - service
      properties:
        name:
          title: Repository Name
          type: string
          description: The name of the repository
          ui:autofocus: true
          ui:options:
            rows: 5
        service:
          title: Service Name
          type: string
          description: The name of the service
          ui:options:
            rows: 5
  steps:
    - id: publish-azure
      name: Publish to Azure DevOps
      action: publish:azure
      input:
        allowedHosts: ["dev.azure.com"]
        description: This is ${{ parameters.name }}
        repoUrl: "dev.azure.com?repo=${{ parameters.name }}&organization=luishenrique92250483&project=backstage"
        project: backstage
        organization: luishenrique92250483

    - id: commit-changes
      name: Create Commit with files
      action: azure:create-commit
      input:
        repository: ${{ parameters.name }}
        organization: luishenrique92250483
        project: backstage
        branch: master
        fileList:
          - filePath: "config/info"
            fileType: "json"
            content: '{"name": "${{ parameters.name }}", "service": "${{ parameters.name }}"}'
          - filePath: "README"
            fileType: "md"
            content: "# ${{ parameters.name }} Service\n\nThis repository contains the **${{ parameters.name }}** service."

    - id: create-branch
      name: Create Branch
      action: azure:create-branch
      input:
        repository: ${{ parameters.name }}
        organization: luishenrique92250483
        project: backstage
        branchNames: ["develop", "qa", "uat"]

  output:
    links:
      - title: Repository
        url: ${{ steps['publish-azure'].output.remoteUrl }}?path=%2F
